name: Deploy to EC2 via AWS CLI

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS_SECRET }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload Files to EC2 Using SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters 'commands=["sudo rm -f /usr/share/nginx/html/index.html", "sudo aws s3 cp s3://oym2025bucket/pullo/ /usr/share/nginx/html/ --recursive"]' \
            --comment "Deploy new code" \
            --output text
