name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      USER_NAME: ${{ secrets.EC2_USER }}
      HOSTNAME: ${{ secrets.EC2_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

      - name: Deploy to EC2 and Remove index.html
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
          rm -f /usr/share/nginx/html/index.html  # Delete existing index.html
EOF

          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i private_key" ./ ${USER_NAME}@${HOSTNAME}:/usr/share/nginx/html/
